language: cpp

os:
  - linux
  - osx

osx_image: xcode7

compiler:
  - clang
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.0-Linux-x86_64.tar.gz
      && tar -xzf cmake-3.5.0-Linux-x86_64.tar.gz
      && sudo cp -fR cmake-3.5.0-Linux-x86_64/* /usr
      && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-get update -qq
      && sudo apt-get install -qq -y --force-yes gcc-5 g++-5
      && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
      && sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    brew update
      && ((brew list -1 | grep -q "^$cmake\$") || brew install cmake)
      && (brew outdated cmake || brew upgrade cmake)
      && cmake --version;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - cmake --build .
